#!/bin/bash
# Single source of truth for all secrets.
# Edit .env, then run this script to propagate keys to Android and iOS.
#
# Usage: ./setup-secrets.sh

set -euo pipefail
ROOT="$(cd "$(dirname "$0")" && pwd)"
ENV="$ROOT/.env"
LOCAL_PROPS="$ROOT/autolife_android_client/local.properties"
XCCONFIG="$ROOT/autolife_android_client/iosApp/AutoLife/Secrets.xcconfig"

if [ ! -f "$ENV" ]; then
  echo "ERROR: .env not found. Create it from the template in docs/rotate-secrets.md."
  exit 1
fi

# Load .env without exporting to shell (safe — no subshell contamination)
_get() { grep "^${1}=" "$ENV" 2>/dev/null | head -1 | cut -d= -f2-; }

GEMINI_API_KEY=$(_get GEMINI_API_KEY)
MAPS_API_KEY=$(_get MAPS_API_KEY)
BACKEND_URL=$(_get BACKEND_URL)
BACKEND_URL="${BACKEND_URL:-http://10.0.2.2:8000}"

# ── Android: local.properties ─────────────────────────────────────────────────
# Preserve sdk.dir (machine-specific, not in .env)
SDK_DIR=$(grep "^sdk.dir=" "$LOCAL_PROPS" 2>/dev/null | head -1 | cut -d= -f2- || true)

{
  echo "# Auto-generated by setup-secrets.sh — edit .env instead."
  [ -n "$SDK_DIR" ] && echo "sdk.dir=$SDK_DIR"
  echo "GEMINI_API_KEY=$GEMINI_API_KEY"
  echo "MAPS_API_KEY=$MAPS_API_KEY"
  echo "BACKEND_URL=$BACKEND_URL"
} > "$LOCAL_PROPS"

# ── iOS: Secrets.xcconfig ─────────────────────────────────────────────────────
{
  echo "// Auto-generated by setup-secrets.sh — edit .env instead."
  echo "GEMINI_API_KEY = $GEMINI_API_KEY"
  echo "MAPS_API_KEY = $MAPS_API_KEY"
} > "$XCCONFIG"

echo "Done."
echo "  → $LOCAL_PROPS"
echo "  → $XCCONFIG"
